apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-chatbot
  labels:
    app: todo-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-chatbot
  template:
    metadata:
      labels:
        app: todo-chatbot
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "todo-chatbot"
        dapr.io/app-port: "8000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: todo-chatbot
        image: todochatbotregistry.azurecr.io/todo-chatbot:latest
        ports:
        - containerPort: 8000
        env:
        - name: DAPR_HTTP_ENDPOINT
          value: "http://127.0.0.1:3500"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-chatbot-service
spec:
  selector:
    app: todo-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
